import type { Question } from "../types/question";

export const conanQuestions: Question[] = [
  {
    id: 1,
    contents: "江戸川コナンの本当の名前は？",
    options: [
      { id: 1, text: "工藤新一" },
      { id: 2, text: "服部平次" },
      { id: 3, text: "白馬探" },
      { id: 4, text: "怪盗キッド" },
    ],
    answerId: 1,
  },
  {
    id: 2,
    contents: "工藤新一を小さくした薬の名前は？",
    options: [
      { id: 1, text: "APTX4869" },
      { id: 2, text: "APTX4896" },
      { id: 3, text: "PX4869" },
      { id: 4, text: "APTX9999" },
    ],
    answerId: 1,
  },
  {
    id: 3,
    contents: "毛利蘭と工藤新一が通う高校は？",
    options: [
      { id: 1, text: "帝丹高校" },
      { id: 2, text: "米花高校" },
      { id: 3, text: "杯戸高校" },
      { id: 4, text: "東都高校" },
    ],
    answerId: 1,
  },
  {
    id: 4,
    contents: "毛利小五郎の職業は？",
    options: [
      { id: 1, text: "刑事" },
      { id: 2, text: "弁護士" },
      { id: 3, text: "私立探偵" },
      { id: 4, text: "医者" },
    ],
    answerId: 3,
  },
  {
    id: 5,
    contents: "阿笠博士がコナンに作った蝶ネクタイ型変声機で変えられるのは？",
    options: [
      { id: 1, text: "服装" },
      { id: 2, text: "声" },
      { id: 3, text: "髪型" },
      { id: 4, text: "身長" },
    ],
    answerId: 2,
  },
  {
    id: 6,
    contents: "関西の高校生探偵として有名なのは？",
    options: [
      { id: 1, text: "白馬探" },
      { id: 2, text: "遠山和葉" },
      { id: 3, text: "服部平次" },
      { id: 4, text: "目暮十三" },
    ],
    answerId: 3,
  },
  {
    id: 7,
    contents: "怪盗キッドの本名は？",
    options: [
      { id: 1, text: "黒羽快斗" },
      { id: 2, text: "工藤新一" },
      { id: 3, text: "服部平次" },
      { id: 4, text: "安室透" },
    ],
    answerId: 1,
  },
  {
    id: 8,
    contents: "少年探偵団のメンバーではないのは？",
    options: [
      { id: 1, text: "吉田歩美" },
      { id: 2, text: "円谷光彦" },
      { id: 3, text: "小嶋元太" },
      { id: 4, text: "遠山和葉" },
    ],
    answerId: 4,
  },
  {
    id: 9,
    contents: "灰原哀の組織時代のコードネームは？",
    options: [
      { id: 1, text: "シェリー" },
      { id: 2, text: "ベルモット" },
      { id: 3, text: "キャンティ" },
      { id: 4, text: "キール" },
    ],
    answerId: 1,
  },
  {
    id: 10,
    contents: "警視庁の刑事でコナンたちとよく関わる警部は？",
    options: [
      { id: 1, text: "高木渉" },
      { id: 2, text: "目暮十三" },
      { id: 3, text: "佐藤美和子" },
      { id: 4, text: "白鳥任三郎" },
    ],
    answerId: 2,
  },
  {
    id: 11,
    contents: "コナンが敵を眠らせる時によく使う道具は？",
    options: [
      { id: 1, text: "腕時計型麻酔銃" },
      { id: 2, text: "ターボエンジン" },
      { id: 3, text: "探偵バッジ" },
      { id: 4, text: "変声機" },
    ],
    answerId: 1,
  },
  {
    id: 12,
    contents: "蘭が得意な武道は？",
    options: [
      { id: 1, text: "柔道" },
      { id: 2, text: "剣道" },
      { id: 3, text: "空手" },
      { id: 4, text: "合気道" },
    ],
    answerId: 3,
  },
  {
    id: 13,
    contents: "安室透のもう一つの名前は？",
    options: [
      { id: 1, text: "降谷零" },
      { id: 2, text: "赤井秀一" },
      { id: 3, text: "諸伏景光" },
      { id: 4, text: "風見裕也" },
    ],
    answerId: 1,
  },
  {
    id: 14,
    contents: "FBI捜査官として登場する人物は？",
    options: [
      { id: 1, text: "赤井秀一" },
      { id: 2, text: "毛利小五郎" },
      { id: 3, text: "阿笠博士" },
      { id: 4, text: "鈴木園子" },
    ],
    answerId: 1,
  },
  {
    id: 15,
    contents: "少年探偵団が連絡に使う道具は？",
    options: [
      { id: 1, text: "探偵バッジ" },
      { id: 2, text: "腕時計型麻酔銃" },
      { id: 3, text: "キック力増強シューズ" },
      { id: 4, text: "ターボエンジン付きスケボー" },
    ],
    answerId: 1,
  },
  {
    id: 16,
    contents: "鈴木園子の親友は？",
    options: [
      { id: 1, text: "灰原哀" },
      { id: 2, text: "毛利蘭" },
      { id: 3, text: "遠山和葉" },
      { id: 4, text: "ベルモット" },
    ],
    answerId: 2,
  },
  {
    id: 17,
    contents: "コナンのよく乗る乗り物は？",
    options: [
      { id: 1, text: "バイク" },
      { id: 2, text: "自転車" },
      { id: 3, text: "ターボエンジン付きスケートボード" },
      { id: 4, text: "ヘリコプター" },
    ],
    answerId: 3,
  },
  {
    id: 18,
    contents: "遠山和葉と仲が良い高校生探偵は？",
    options: [
      { id: 1, text: "怪盗キッド" },
      { id: 2, text: "服部平次" },
      { id: 3, text: "工藤新一" },
      { id: 4, text: "白馬探" },
    ],
    answerId: 2,
  },
  {
    id: 19,
    contents: "阿笠博士の発明品ではないのは？",
    options: [
      { id: 1, text: "探偵バッジ" },
      { id: 2, text: "キック力増強シューズ" },
      { id: 3, text: "ターボエンジン付きスケートボード" },
      { id: 4, text: "どこでもドア" },
    ],
    answerId: 4,
  },
  {
    id: 20,
    contents: "コナンが住むことになる探偵事務所の名前は？",
    options: [
      { id: 1, text: "工藤探偵事務所" },
      { id: 2, text: "毛利探偵事務所" },
      { id: 3, text: "米花探偵事務所" },
      { id: 4, text: "帝丹探偵事務所" },
    ],
    answerId: 2,
  },
  {
    id: 21,
    contents: "黒ずくめの組織のボスのメールアドレスに含まれる童謡は？",
    options: [
      { id: 1, text: "七つの子" },
      { id: 2, text: "赤とんぼ" },
      { id: 3, text: "ふるさと" },
      { id: 4, text: "シャボン玉" },
    ],
    answerId: 1,
  },
  {
    id: 22,
    contents: "灰原哀の本名は？",
    options: [
      { id: 1, text: "宮野志保" },
      { id: 2, text: "宮野明美" },
      { id: 3, text: "宮野エレーナ" },
      { id: 4, text: "宮野厚司" },
    ],
    answerId: 1,
  },
  {
    id: 23,
    contents: "安室透が公安警察として活動する際の本名は？",
    options: [
      { id: 1, text: "降谷零" },
      { id: 2, text: "諸伏景光" },
      { id: 3, text: "風見裕也" },
      { id: 4, text: "黒田兵衛" },
    ],
    answerId: 1,
  },
  {
    id: 24,
    contents: "赤井秀一が黒ずくめの組織に潜入していた時のコードネームは？",
    options: [
      { id: 1, text: "ライ" },
      { id: 2, text: "バーボン" },
      { id: 3, text: "キール" },
      { id: 4, text: "スコッチ" },
    ],
    answerId: 1,
  },
  {
    id: 25,
    contents: "工藤優作の職業は？",
    options: [
      { id: 1, text: "推理小説家" },
      { id: 2, text: "警察官" },
      { id: 3, text: "弁護士" },
      { id: 4, text: "大学教授" },
    ],
    answerId: 1,
  },
  {
    id: 26,
    contents: "赤井秀一の妹の名前は？",
    options: [
      { id: 1, text: "世良真純" },
      { id: 2, text: "鈴木園子" },
      { id: 3, text: "宮野明美" },
      { id: 4, text: "榎本梓" },
    ],
    answerId: 1,
  },
  {
    id: 27,
    contents: "ベルモットが『シルバーブレット』と呼んでいる人物は？",
    options: [
      { id: 1, text: "江戸川コナン" },
      { id: 2, text: "目暮十三" },
      { id: 3, text: "小嶋元太" },
      { id: 4, text: "毛利小五郎" },
    ],
    answerId: 1,
  },
  {
    id: 28,
    contents: "服部平次の父親の役職は？",
    options: [
      { id: 1, text: "大阪府警本部長" },
      { id: 2, text: "警視総監" },
      { id: 3, text: "検事総長" },
      { id: 4, text: "警察庁長官" },
    ],
    answerId: 1,
  },
  {
    id: 29,
    contents: "宮野明美が組織内で名乗っていた偽名は？",
    options: [
      { id: 1, text: "広田雅美" },
      { id: 2, text: "沖矢昴" },
      { id: 3, text: "榎本梓" },
      { id: 4, text: "水無怜奈" },
    ],
    answerId: 1,
  },
  {
    id: 30,
    contents: "警察学校組でスコッチとして潜入していた人物は？",
    options: [
      { id: 1, text: "諸伏景光" },
      { id: 2, text: "伊達航" },
      { id: 3, text: "萩原研二" },
      { id: 4, text: "松田陣平" },
    ],
    answerId: 1,
  },
  {
    id: 31,
    contents: "怪盗キッドの初代の正体は？",
    options: [
      { id: 1, text: "黒羽盗一" },
      { id: 2, text: "黒羽快斗" },
      { id: 3, text: "寺井黄之助" },
      { id: 4, text: "白馬探" },
    ],
    answerId: 1,
  },
  {
    id: 32,
    contents: "沖矢昴の正体は？",
    options: [
      { id: 1, text: "赤井秀一" },
      { id: 2, text: "安室透" },
      { id: 3, text: "黒田兵衛" },
      { id: 4, text: "羽田秀吉" },
    ],
    answerId: 1,
  },
  {
    id: 33,
    contents: "羽田秀吉の職業は？",
    options: [
      { id: 1, text: "将棋棋士" },
      { id: 2, text: "刑事" },
      { id: 3, text: "弁護士" },
      { id: 4, text: "医師" },
    ],
    answerId: 1,
  },
  {
    id: 34,
    contents: "世良真純がよく持ち歩いているスマホ越しの人物は？",
    options: [
      { id: 1, text: "メアリー世良" },
      { id: 2, text: "ベルモット" },
      { id: 3, text: "妃英理" },
      { id: 4, text: "宮野エレーナ" },
    ],
    answerId: 1,
  },
  {
    id: 35,
    contents: "コードネーム『キール』として潜入しているCIA捜査官は？",
    options: [
      { id: 1, text: "水無怜奈" },
      { id: 2, text: "ベルモット" },
      { id: 3, text: "キャンティ" },
      { id: 4, text: "シェリー" },
    ],
    answerId: 1,
  },
  {
    id: 36,
    contents: "コナンがサッカーボールを強力に蹴るために使用する道具は？",
    options: [
      { id: 1, text: "キック力増強シューズ" },
      { id: 2, text: "探偵バッジ" },
      { id: 3, text: "変声機" },
      { id: 4, text: "伸縮サスペンダー" },
    ],
    answerId: 1,
  },
  {
    id: 37,
    contents: "黒ずくめの組織のジンが愛用する車は？",
    options: [
      { id: 1, text: "ポルシェ356A" },
      { id: 2, text: "フェアレディZ" },
      { id: 3, text: "スカイラインGT-R" },
      { id: 4, text: "セリカGT-FOUR" },
    ],
    answerId: 1,
  },
  {
    id: 38,
    contents: "羽田秀吉と赤井秀一の関係は？",
    options: [
      { id: 1, text: "兄弟" },
      { id: 2, text: "いとこ" },
      { id: 3, text: "親子" },
      { id: 4, text: "幼なじみ" },
    ],
    answerId: 1,
  },
  {
    id: 39,
    contents: "妃英理の職業は？",
    options: [
      { id: 1, text: "弁護士" },
      { id: 2, text: "検察官" },
      { id: 3, text: "裁判官" },
      { id: 4, text: "政治家" },
    ],
    answerId: 1,
  },
  {
    id: 40,
    contents: "黒ずくめの組織のボスとして判明している人物は？",
    options: [
      { id: 1, text: "烏丸蓮耶" },
      { id: 2, text: "黒田兵衛" },
      { id: 3, text: "脇田兼則" },
      { id: 4, text: "大岡紅葉" },
    ],
    answerId: 1,
  },
];
