import type { Question } from "../types/question";

export const englishQuestions: Question[] = [
  {
    id: 1,
    contents: "「りんご」は英語で？",
    options: [
      { id: 1, text: "apple" },
      { id: 2, text: "aplle" },
      { id: 3, text: "appel" },
      { id: 4, text: "aple" },
    ],
    answerId: 1,
  },
  {
    id: 2,
    contents: "「犬」は英語で？",
    options: [
      { id: 1, text: "cat" },
      { id: 2, text: "dog" },
      { id: 3, text: "bird" },
      { id: 4, text: "fish" },
    ],
    answerId: 2,
  },
  {
    id: 3,
    contents: "「学校」は英語で？",
    options: [
      { id: 1, text: "school" },
      { id: 2, text: "scool" },
      { id: 3, text: "schole" },
      { id: 4, text: "shool" },
    ],
    answerId: 1,
  },
  {
    id: 4,
    contents: "「私は学生です。」の英訳は？",
    options: [
      { id: 1, text: "I is a student." },
      { id: 2, text: "I am a student." },
      { id: 3, text: "I are a student." },
      { id: 4, text: "Me am a student." },
    ],
    answerId: 2,
  },
  {
    id: 5,
    contents: "be動詞として正しいものは？",
    options: [
      { id: 1, text: "am" },
      { id: 2, text: "play" },
      { id: 3, text: "study" },
      { id: 4, text: "like" },
    ],
    answerId: 1,
  },
  {
    id: 6,
    contents: "「彼は野球をします。」の英訳は？",
    options: [
      { id: 1, text: "He play baseball." },
      { id: 2, text: "He plays baseball." },
      { id: 3, text: "He playing baseball." },
      { id: 4, text: "He played baseball." },
    ],
    answerId: 2,
  },
  {
    id: 7,
    contents: "「私はサッカーが好きです。」の英訳は？",
    options: [
      { id: 1, text: "I like soccer." },
      { id: 2, text: "I likes soccer." },
      { id: 3, text: "I am like soccer." },
      { id: 4, text: "I liking soccer." },
    ],
    answerId: 1,
  },
  {
    id: 8,
    contents: "Mondayの意味は？",
    options: [
      { id: 1, text: "火曜日" },
      { id: 2, text: "木曜日" },
      { id: 3, text: "月曜日" },
      { id: 4, text: "金曜日" },
    ],
    answerId: 3,
  },
  {
    id: 9,
    contents: "正しいつづりはどれ？",
    options: [
      { id: 1, text: "becouse" },
      { id: 2, text: "because" },
      { id: 3, text: "becaus" },
      { id: 4, text: "becausee" },
    ],
    answerId: 2,
  },
  {
    id: 10,
    contents: "「私はテニスをします。」の英訳は？",
    options: [
      { id: 1, text: "I play tennis." },
      { id: 2, text: "I plays tennis." },
      { id: 3, text: "I am play tennis." },
      { id: 4, text: "I playing tennis." },
    ],
    answerId: 1,
  },
    {
    id: 11,
    contents: "「あなたはサッカーが好きですか。」の英訳は？",
    options: [
      { id: 1, text: "Do you like soccer?" },
      { id: 2, text: "Are you like soccer?" },
      { id: 3, text: "You like soccer?" },
      { id: 4, text: "Does you like soccer?" },
    ],
    answerId: 1,
  },
  {
    id: 12,
    contents: "「私は野球が好きではありません。」の英訳は？",
    options: [
      { id: 1, text: "I don't like baseball." },
      { id: 2, text: "I not like baseball." },
      { id: 3, text: "I doesn't like baseball." },
      { id: 4, text: "I am not like baseball." },
    ],
    answerId: 1,
  },
  {
    id: 13,
    contents: "「3」を英語で表すと？",
    options: [
      { id: 1, text: "three" },
      { id: 2, text: "tree" },
      { id: 3, text: "there" },
      { id: 4, text: "thrie" },
    ],
    answerId: 1,
  },
  {
    id: 14,
    contents: "Fridayの意味は？",
    options: [
      { id: 1, text: "火曜日" },
      { id: 2, text: "金曜日" },
      { id: 3, text: "木曜日" },
      { id: 4, text: "日曜日" },
    ],
    answerId: 2,
  },
  {
    id: 15,
    contents: "正しいつづりはどれ？",
    options: [
      { id: 1, text: "beautiful" },
      { id: 2, text: "beatiful" },
      { id: 3, text: "beautifull" },
      { id: 4, text: "beautyful" },
    ],
    answerId: 1,
  },
  {
    id: 16,
    contents: "「彼女はピアノを弾きます。」の英訳は？",
    options: [
      { id: 1, text: "She play the piano." },
      { id: 2, text: "She plays the piano." },
      { id: 3, text: "She playing the piano." },
      { id: 4, text: "She played the piano." },
    ],
    answerId: 2,
  },
  {
    id: 17,
    contents: "Januaryの意味は？",
    options: [
      { id: 1, text: "1月" },
      { id: 2, text: "2月" },
      { id: 3, text: "3月" },
      { id: 4, text: "12月" },
    ],
    answerId: 1,
  },
  {
    id: 18,
    contents: "「彼は先生ですか。」の英訳は？",
    options: [
      { id: 1, text: "Is he a teacher?" },
      { id: 2, text: "Are he a teacher?" },
      { id: 3, text: "Do he a teacher?" },
      { id: 4, text: "He is a teacher?" },
    ],
    answerId: 1,
  },
  {
    id: 19,
    contents: "「私たちは友達です。」の英訳は？",
    options: [
      { id: 1, text: "We am friends." },
      { id: 2, text: "We is friends." },
      { id: 3, text: "We are friends." },
      { id: 4, text: "We be friends." },
    ],
    answerId: 3,
  },
  {
    id: 20,
    contents: "正しいつづりはどれ？",
    options: [
      { id: 1, text: "library" },
      { id: 2, text: "libary" },
      { id: 3, text: "liblary" },
      { id: 4, text: "libraly" },
    ],
    answerId: 1,
  },
    {
    id: 21,
    contents: "「私は泳ぐことができます。」の英訳は？",
    options: [
      { id: 1, text: "I can swim." },
      { id: 2, text: "I am swim." },
      { id: 3, text: "I can swims." },
      { id: 4, text: "I swim can." },
    ],
    answerId: 1,
  },
  {
    id: 22,
    contents: "「窓を開けてください。」の英訳は？",
    options: [
      { id: 1, text: "Open the window." },
      { id: 2, text: "Opens the window." },
      { id: 3, text: "You open the window." },
      { id: 4, text: "Opening the window." },
    ],
    answerId: 1,
  },
  {
    id: 23,
    contents: "What time is it? の意味は？",
    options: [
      { id: 1, text: "今日は何曜日ですか。" },
      { id: 2, text: "何時ですか。" },
      { id: 3, text: "どこにいますか。" },
      { id: 4, text: "誰ですか。" },
    ],
    answerId: 2,
  },
  {
    id: 24,
    contents: "「今日は晴れです。」の英訳は？",
    options: [
      { id: 1, text: "It is sunny today." },
      { id: 2, text: "It sunny today." },
      { id: 3, text: "Today is sun." },
      { id: 4, text: "It are sunny today." },
    ],
    answerId: 1,
  },
  {
    id: 25,
    contents: "Where do you live? の意味は？",
    options: [
      { id: 1, text: "何歳ですか。" },
      { id: 2, text: "どこに住んでいますか。" },
      { id: 3, text: "何を食べますか。" },
      { id: 4, text: "どこへ行きますか。" },
    ],
    answerId: 2,
  },
  {
    id: 26,
    contents: "「数学」を表す英語は？",
    options: [
      { id: 1, text: "science" },
      { id: 2, text: "music" },
      { id: 3, text: "math" },
      { id: 4, text: "art" },
    ],
    answerId: 3,
  },
  {
    id: 27,
    contents: "「彼は毎日英語を勉強します。」の英訳は？",
    options: [
      { id: 1, text: "He study English every day." },
      { id: 2, text: "He studies English every day." },
      { id: 3, text: "He studying English every day." },
      { id: 4, text: "He studied English every day." },
    ],
    answerId: 2,
  },
  {
    id: 28,
    contents: "正しいつづりはどれ？",
    options: [
      { id: 1, text: "tomorow" },
      { id: 2, text: "tommorrow" },
      { id: 3, text: "tomorrow" },
      { id: 4, text: "tomarrow" },
    ],
    answerId: 3,
  },
  {
    id: 29,
    contents: "「7月」は英語で？",
    options: [
      { id: 1, text: "June" },
      { id: 2, text: "July" },
      { id: 3, text: "August" },
      { id: 4, text: "September" },
    ],
    answerId: 2,
  },
  {
    id: 30,
    contents: "「あなたはピアノを弾けますか。」の英訳は？",
    options: [
      { id: 1, text: "Can you play the piano?" },
      { id: 2, text: "Do you can play the piano?" },
      { id: 3, text: "You can play the piano?" },
      { id: 4, text: "Can play you the piano?" },
    ],
    answerId: 1,
  },
    {
    id: 31,
    contents: "「彼女は私の妹です。」の英訳は？",
    options: [
      { id: 1, text: "She is my sister." },
      { id: 2, text: "She are my sister." },
      { id: 3, text: "He is my sister." },
      { id: 4, text: "She am my sister." },
    ],
    answerId: 1,
  },
  {
    id: 32,
    contents: "they の意味は？",
    options: [
      { id: 1, text: "彼" },
      { id: 2, text: "彼女" },
      { id: 3, text: "彼ら・彼女ら" },
      { id: 4, text: "私たち" },
    ],
    answerId: 3,
  },
  {
    id: 33,
    contents: "「ねこは机の下にいます。」の英訳は？",
    options: [
      { id: 1, text: "The cat is under the desk." },
      { id: 2, text: "The cat is on the desk." },
      { id: 3, text: "The cat is in the desk." },
      { id: 4, text: "The cat are under the desk." },
    ],
    answerId: 1,
  },
  {
    id: 34,
    contents: "under の意味は？",
    options: [
      { id: 1, text: "上に" },
      { id: 2, text: "中に" },
      { id: 3, text: "下に" },
      { id: 4, text: "後ろに" },
    ],
    answerId: 3,
  },
  {
    id: 35,
    contents: "正しいつづりはどれ？",
    options: [
      { id: 1, text: "friend" },
      { id: 2, text: "freind" },
      { id: 3, text: "frend" },
      { id: 4, text: "friend" },
    ],
    answerId: 1,
  },
  {
    id: 36,
    contents: "「彼はいつも早く起きます。」の英訳は？",
    options: [
      { id: 1, text: "He always gets up early." },
      { id: 2, text: "He get up always early." },
      { id: 3, text: "He always get up early." },
      { id: 4, text: "He gets up always early." },
    ],
    answerId: 1,
  },
  {
    id: 37,
    contents: "What is this? の意味は？",
    options: [
      { id: 1, text: "これは誰ですか。" },
      { id: 2, text: "これは何ですか。" },
      { id: 3, text: "これはどこですか。" },
      { id: 4, text: "これはいつですか。" },
    ],
    answerId: 2,
  },
  {
    id: 38,
    contents: "「彼らは今サッカーをしています。」の英訳は？",
    options: [
      { id: 1, text: "They play soccer now." },
      { id: 2, text: "They are playing soccer now." },
      { id: 3, text: "They playing soccer now." },
      { id: 4, text: "They is playing soccer now." },
    ],
    answerId: 2,
  },
  {
    id: 39,
    contents: "現在進行形の形として正しいものは？",
    options: [
      { id: 1, text: "be動詞 + 動詞ing" },
      { id: 2, text: "do + 動詞" },
      { id: 3, text: "動詞 + s" },
      { id: 4, text: "be動詞のみ" },
    ],
    answerId: 1,
  },
  {
    id: 40,
    contents: "正しいつづりはどれ？",
    options: [
      { id: 1, text: "interesting" },
      { id: 2, text: "intersting" },
      { id: 3, text: "interestingg" },
      { id: 4, text: "intresting" },
    ],
    answerId: 1,
  },
    {
    id: 41,
    contents: "「私の母は夕食を作っています。」の英訳は？",
    options: [
      { id: 1, text: "My mother is cooking dinner." },
      { id: 2, text: "My mother cooks dinner now." },
      { id: 3, text: "My mother cooking dinner." },
      { id: 4, text: "My mother are cooking dinner." },
    ],
    answerId: 1,
  },
  {
    id: 42,
    contents: "「あなたはどこで英語を勉強しますか。」の英訳は？",
    options: [
      { id: 1, text: "Where do you study English?" },
      { id: 2, text: "What do you study English?" },
      { id: 3, text: "Where are you study English?" },
      { id: 4, text: "Do you where study English?" },
    ],
    answerId: 1,
  },
  {
    id: 43,
    contents: "「彼はテレビを見ていません。」の英訳は？",
    options: [
      { id: 1, text: "He doesn't watch TV." },
      { id: 2, text: "He don't watch TV." },
      { id: 3, text: "He not watch TV." },
      { id: 4, text: "He isn't watch TV." },
    ],
    answerId: 1,
  },
  {
    id: 44,
    contents: "正しいつづりはどれ？",
    options: [
      { id: 1, text: "different" },
      { id: 2, text: "diffrent" },
      { id: 3, text: "defferent" },
      { id: 4, text: "diferent" },
    ],
    answerId: 1,
  },
  {
    id: 45,
    contents: "「彼女は毎週日曜日にテニスをします。」の英訳は？",
    options: [
      { id: 1, text: "She plays tennis every Sunday." },
      { id: 2, text: "She play tennis every Sunday." },
      { id: 3, text: "She is play tennis every Sunday." },
      { id: 4, text: "She playing tennis every Sunday." },
    ],
    answerId: 1,
  },
  {
    id: 46,
    contents: "「図書館」は英語で？",
    options: [
      { id: 1, text: "hospital" },
      { id: 2, text: "library" },
      { id: 3, text: "station" },
      { id: 4, text: "museum" },
    ],
    answerId: 2,
  },
  {
    id: 47,
    contents: "What subject do you like? の意味は？",
    options: [
      { id: 1, text: "どのスポーツが好きですか。" },
      { id: 2, text: "どの教科が好きですか。" },
      { id: 3, text: "どの食べ物が好きですか。" },
      { id: 4, text: "どの先生が好きですか。" },
    ],
    answerId: 2,
  },
  {
    id: 48,
    contents: "「私は英語を話すことができます。」の英訳は？",
    options: [
      { id: 1, text: "I can speak English." },
      { id: 2, text: "I can speaks English." },
      { id: 3, text: "I speak can English." },
      { id: 4, text: "I am speak English." },
    ],
    answerId: 1,
  },
  {
    id: 49,
    contents: "正しいつづりはどれ？",
    options: [
      { id: 1, text: "favorite" },
      { id: 2, text: "favoritee" },
      { id: 3, text: "favorit" },
      { id: 4, text: "favarite" },
    ],
    answerId: 1,
  },
  {
    id: 50,
    contents: "「あなたは昨日学校に行きましたか。」の英訳は？",
    options: [
      { id: 1, text: "Did you go to school yesterday?" },
      { id: 2, text: "Do you go to school yesterday?" },
      { id: 3, text: "Were you go to school yesterday?" },
      { id: 4, text: "Did you went to school yesterday?" },
    ],
    answerId: 1,
  },
];