import type { Question } from "../types/question";

export const triviaQuestions: Question[] = [
  {
    id: 1,
    contents: "日本の首都は？",
    options: [
      { id: 1, text: "大阪" },
      { id: 2, text: "東京" },
      { id: 3, text: "名古屋" },
      { id: 4, text: "福岡" },
    ],
    answerId: 2,
  },
  {
    id: 2,
    contents: "世界最大の動物は？",
    options: [
      { id: 1, text: "アフリカゾウ" },
      { id: 2, text: "シロナガスクジラ" },
      { id: 3, text: "キリン" },
      { id: 4, text: "サイ" },
    ],
    answerId: 2,
  },
  {
    id: 3,
    contents: "タコの足は何本？",
    options: [
      { id: 1, text: "6本" },
      { id: 2, text: "8本" },
      { id: 3, text: "10本" },
      { id: 4, text: "12本" },
    ],
    answerId: 2,
  },
  {
    id: 4,
    contents: "1年は通常何日？",
    options: [
      { id: 1, text: "360日" },
      { id: 2, text: "365日" },
      { id: 3, text: "370日" },
      { id: 4, text: "400日" },
    ],
    answerId: 2,
  },
  {
    id: 5,
    contents: "コアラが主に食べるものは？",
    options: [
      { id: 1, text: "竹" },
      { id: 2, text: "ユーカリの葉" },
      { id: 3, text: "魚" },
      { id: 4, text: "木の実" },
    ],
    answerId: 2,
  },
  {
    id: 6,
    contents: "富士山のある都道府県は？",
    options: [
      { id: 1, text: "北海道" },
      { id: 2, text: "沖縄県" },
      { id: 3, text: "静岡県" },
      { id: 4, text: "香川県" },
    ],
    answerId: 3,
  },
  {
    id: 7,
    contents: "信号の『進め』の色は？",
    options: [
      { id: 1, text: "青" },
      { id: 2, text: "赤" },
      { id: 3, text: "黄" },
      { id: 4, text: "白" },
    ],
    answerId: 1,
  },
  {
    id: 8,
    contents: "ペンギンは何類？",
    options: [
      { id: 1, text: "魚類" },
      { id: 2, text: "鳥類" },
      { id: 3, text: "哺乳類" },
      { id: 4, text: "爬虫類" },
    ],
    answerId: 2,
  },
  {
    id: 9,
    contents: "地球は太陽の周りを約何日で一周する？",
    options: [
      { id: 1, text: "30日" },
      { id: 2, text: "180日" },
      { id: 3, text: "365日" },
      { id: 4, text: "730日" },
    ],
    answerId: 3,
  },
  {
    id: 10,
    contents: "キリンの特徴は？",
    options: [
      { id: 1, text: "首が長い" },
      { id: 2, text: "羽がある" },
      { id: 3, text: "海に住む" },
      { id: 4, text: "角が10本ある" },
    ],
    answerId: 1,
  },
  {
    id: 11,
    contents: "日本で最も高い山は？",
    options: [
      { id: 1, text: "阿蘇山" },
      { id: 2, text: "富士山" },
      { id: 3, text: "高尾山" },
      { id: 4, text: "桜島" },
    ],
    answerId: 2,
  },
  {
    id: 12,
    contents: "チーターが得意なのは？",
    options: [
      { id: 1, text: "泳ぐこと" },
      { id: 2, text: "飛ぶこと" },
      { id: 3, text: "速く走ること" },
      { id: 4, text: "穴を掘ること" },
    ],
    answerId: 3,
  },
  {
    id: 13,
    contents: "海で暮らす哺乳類は？",
    options: [
      { id: 1, text: "イルカ" },
      { id: 2, text: "サメ" },
      { id: 3, text: "イワシ" },
      { id: 4, text: "タコ" },
    ],
    answerId: 1,
  },
  {
    id: 14,
    contents: "五輪マークはいくつの輪でできている？",
    options: [
      { id: 1, text: "3つ" },
      { id: 2, text: "4つ" },
      { id: 3, text: "5つ" },
      { id: 4, text: "6つ" },
    ],
    answerId: 3,
  },
  {
    id: 15,
    contents: "パンダの主食は？",
    options: [
      { id: 1, text: "魚" },
      { id: 2, text: "竹" },
      { id: 3, text: "肉" },
      { id: 4, text: "米" },
    ],
    answerId: 2,
  },
  {
    id: 16,
    contents: "サッカーで1チームが同時に出場できる人数は？",
    options: [
      { id: 1, text: "9人" },
      { id: 2, text: "10人" },
      { id: 3, text: "11人" },
      { id: 4, text: "12人" },
    ],
    answerId: 3,
  },
  {
    id: 17,
    contents: "人間の歯は大人になると通常何本？",
    options: [
      { id: 1, text: "20本" },
      { id: 2, text: "24本" },
      { id: 3, text: "28本" },
      { id: 4, text: "32本" },
    ],
    answerId: 4,
  },
  {
    id: 18,
    contents: "カンガルーの赤ちゃんを育てる場所は？",
    options: [
      { id: 1, text: "耳の中" },
      { id: 2, text: "お腹の袋" },
      { id: 3, text: "背中" },
      { id: 4, text: "尻尾" },
    ],
    answerId: 2,
  },
  {
    id: 19,
    contents: "世界最大の海洋は？",
    options: [
      { id: 1, text: "インド洋" },
      { id: 2, text: "大西洋" },
      { id: 3, text: "太平洋" },
      { id: 4, text: "北極海" },
    ],
    answerId: 3,
  },
  {
    id: 20,
    contents: "ハチミツを作る昆虫は？",
    options: [
      { id: 1, text: "アリ" },
      { id: 2, text: "ハチ" },
      { id: 3, text: "チョウ" },
      { id: 4, text: "カブトムシ" },
    ],
    answerId: 2,
  },
  {
    id: 21,
    contents: "大谷翔平選手が主にプレーしているスポーツは？",
    options: [
      { id: 1, text: "サッカー" },
      { id: 2, text: "野球" },
      { id: 3, text: "バスケットボール" },
      { id: 4, text: "テニス" },
    ],
    answerId: 2,
  },
  {
    id: 22,
    contents: "サッカー日本代表の愛称は？",
    options: [
      { id: 1, text: "サムライブルー" },
      { id: 2, text: "ブルータイガー" },
      { id: 3, text: "ジャパンスターズ" },
      { id: 4, text: "ニッポンイレブン" },
    ],
    answerId: 1,
  },
  {
    id: 23,
    contents: "テニスの四大大会を総称して何という？",
    options: [
      { id: 1, text: "マスターズ" },
      { id: 2, text: "グランドスラム" },
      { id: 3, text: "スーパーシリーズ" },
      { id: 4, text: "ワールドカップ" },
    ],
    answerId: 2,
  },
  {
    id: 24,
    contents: "オリンピックのシンボルマークは何色の輪で構成される？",
    options: [
      { id: 1, text: "3色" },
      { id: 2, text: "4色" },
      { id: 3, text: "5色" },
      { id: 4, text: "6色" },
    ],
    answerId: 3,
  },
  {
    id: 25,
    contents: "野球で1チームが守備につく人数は？",
    options: [
      { id: 1, text: "7人" },
      { id: 2, text: "8人" },
      { id: 3, text: "9人" },
      { id: 4, text: "10人" },
    ],
    answerId: 3,
  },
  {
    id: 26,
    contents: "『千と千尋の神隠し』を制作したスタジオは？",
    options: [
      { id: 1, text: "スタジオジブリ" },
      { id: 2, text: "東映アニメーション" },
      { id: 3, text: "京都アニメーション" },
      { id: 4, text: "サンライズ" },
    ],
    answerId: 1,
  },
  {
    id: 27,
    contents: "ドラえもんの好きな食べ物は？",
    options: [
      { id: 1, text: "どら焼き" },
      { id: 2, text: "たい焼き" },
      { id: 3, text: "ケーキ" },
      { id: 4, text: "メロンパン" },
    ],
    answerId: 1,
  },
  {
    id: 28,
    contents: "『名探偵コナン』の主人公の本名は？",
    options: [
      { id: 1, text: "服部平次" },
      { id: 2, text: "怪盗キッド" },
      { id: 3, text: "工藤新一" },
      { id: 4, text: "安室透" },
    ],
    answerId: 3,
  },
  {
    id: 29,
    contents: "『ONE PIECE』で主人公ルフィが目指しているのは？",
    options: [
      { id: 1, text: "海軍大将" },
      { id: 2, text: "海賊王" },
      { id: 3, text: "国王" },
      { id: 4, text: "冒険家" },
    ],
    answerId: 2,
  },
  {
    id: 30,
    contents: "『鬼滅の刃』の主人公は？",
    options: [
      { id: 1, text: "我妻善逸" },
      { id: 2, text: "竈門炭治郎" },
      { id: 3, text: "嘴平伊之助" },
      { id: 4, text: "冨岡義勇" },
    ],
    answerId: 2,
  },
  {
    id: 31,
    contents: "日本の首都は？",
    options: [
      { id: 1, text: "大阪" },
      { id: 2, text: "東京" },
    ],
    answerId: 2,
  },
  {
    id: 32,
    contents: "富士山があるのは？",
    options: [
      { id: 1, text: "日本" },
      { id: 2, text: "中国" },
      { id: 3, text: "韓国" },
    ],
    answerId: 1,
  },
  {
    id: 33,
    contents: "地球は太陽の周りを回っている。",
    options: [
      { id: 1, text: "○" },
      { id: 2, text: "×" },
    ],
    answerId: 1,
  },
  {
    id: 34,
    contents: "日本の国鳥は？",
    options: [
      { id: 1, text: "キジ" },
      { id: 2, text: "ツル" },
      { id: 3, text: "スズメ" },
      { id: 4, text: "ワシ" },
    ],
    answerId: 1,
  },
  {
    id: 35,
    contents: "日本で最も面積が大きい都道府県は？",
    options: [
      { id: 1, text: "長野県" },
      { id: 2, text: "北海道" },
      { id: 3, text: "岩手県" },
      { id: 4, text: "福島県" },
    ],
    answerId: 2,
  },
  {
    id: 36,
    contents: "信号機の色として使われていない色は？",
    options: [
      { id: 1, text: "赤" },
      { id: 2, text: "青" },
      { id: 3, text: "黄" },
      { id: 4, text: "白" },
    ],
    answerId: 4,
  },
  {
    id: 37,
    contents: "『スーパーマリオ』の主人公は？",
    options: [
      { id: 1, text: "ルイージ" },
      { id: 2, text: "マリオ" },
      { id: 3, text: "ヨッシー" },
    ],
    answerId: 2,
  },
  {
    id: 38,
    contents: "1年は365日である。",
    options: [
      { id: 1, text: "○" },
      { id: 2, text: "×" },
    ],
    answerId: 1,
  },
  {
    id: 39,
    contents: "日本円の通貨記号は？",
    options: [
      { id: 1, text: "$" },
      { id: 2, text: "€" },
      { id: 3, text: "¥" },
    ],
    answerId: 3,
  },
  {
    id: 40,
    contents: "野球でホームランは何点？",
    options: [
      { id: 1, text: "1点" },
      { id: 2, text: "2点" },
      { id: 3, text: "状況による" },
    ],
    answerId: 3,
  },
  {
    id: 41,
    contents: "日本の国花として知られる花は？",
    options: [
      { id: 1, text: "桜" },
      { id: 2, text: "梅" },
      { id: 3, text: "菊" },
      { id: 4, text: "椿" },
      { id: 5, text: "牡丹" },
    ],
    answerId: 1,
  },
  {
    id: 42,
    contents: "海の中で最も大きい動物は？",
    options: [
      { id: 1, text: "シャチ" },
      { id: 2, text: "シロナガスクジラ" },
      { id: 3, text: "ジンベエザメ" },
      { id: 4, text: "マッコウクジラ" },
    ],
    answerId: 2,
  },
  {
    id: 43,
    contents: "日本の元号で現在使用されているのは？",
    options: [
      { id: 1, text: "平成" },
      { id: 2, text: "令和" },
    ],
    answerId: 2,
  },
  {
    id: 44,
    contents: "『ポケットモンスター』の主人公として有名なのは？",
    options: [
      { id: 1, text: "サトシ" },
      { id: 2, text: "タケシ" },
      { id: 3, text: "シゲル" },
    ],
    answerId: 1,
  },
  {
    id: 45,
    contents: "地球上で最も広い海は？",
    options: [
      { id: 1, text: "大西洋" },
      { id: 2, text: "太平洋" },
      { id: 3, text: "インド洋" },
      { id: 4, text: "北極海" },
    ],
    answerId: 2,
  },
  {
    id: 46,
    contents: "五輪マークの輪の数は？",
    options: [
      { id: 1, text: "4" },
      { id: 2, text: "5" },
      { id: 3, text: "6" },
    ],
    answerId: 2,
  },
  {
    id: 47,
    contents: "ドラゴンボールの主人公は？",
    options: [
      { id: 1, text: "ベジータ" },
      { id: 2, text: "孫悟空" },
      { id: 3, text: "ピッコロ" },
      { id: 4, text: "クリリン" },
    ],
    answerId: 2,
  },
  {
    id: 48,
    contents: "日本で一番高い山は富士山である。",
    options: [
      { id: 1, text: "○" },
      { id: 2, text: "×" },
    ],
    answerId: 1,
  },
  {
    id: 49,
    contents: "『となりのトトロ』に登場する不思議な生き物は？",
    options: [
      { id: 1, text: "トトロ" },
      { id: 2, text: "ポニョ" },
      { id: 3, text: "ジジ" },
      { id: 4, text: "カルシファー" },
      { id: 5, text: "ムスカ" },
    ],
    answerId: 1,
  },
  {
    id: 50,
    contents: "1メートルは何センチメートル？",
    options: [
      { id: 1, text: "10" },
      { id: 2, text: "100" },
      { id: 3, text: "1000" },
    ],
    answerId: 2,
  },
];
